{
  "hash": "832a40e2a955062689ac009acafbff38",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Conclusions\"\nauthor: \"Your Name\"\ndate: today\nformat:\n  html:\n    code-fold: true\n    toc: true\n    theme: cosmo\n---\n\n## Load Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.5.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(knitr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'knitr' was built under R version 4.5.2\n```\n\n\n:::\n\n```{.r .cell-code}\nearthquake <- readRDS(\"../data/processed/earthquake_clean.rds\")\n```\n:::\n\n\n---\n\n# Summary Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_table <- tibble(\n  Metric = c(\n    \"Total Observations\",\n    \"Unique Stations\",\n    \"States Covered\",\n    \"Mean Magnitude\",\n    \"Magnitude Range\",\n    \"Max Distance\",\n    \"Mean Intensity\"\n  ),\n  Value = c(\n    format(nrow(earthquake), big.mark = \",\"),\n    n_distinct(earthquake$Location),\n    n_distinct(earthquake$State),\n    round(mean(earthquake$Magnitude, na.rm = TRUE), 2),\n    paste0(min(earthquake$Magnitude, na.rm = TRUE), \" to \", \n           max(earthquake$Magnitude, na.rm = TRUE)),\n    paste0(round(max(earthquake$Distance_km, na.rm = TRUE), 0), \" km\"),\n    round(mean(earthquake$Intensity, na.rm = TRUE), 2)\n  )\n)\n\nkable(summary_table, caption = \"Project Summary Statistics\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Project Summary Statistics\n\n|Metric             |Value   |\n|:------------------|:-------|\n|Total Observations |142,083 |\n|Unique Stations    |19416   |\n|States Covered     |67      |\n|Mean Magnitude     |7.41    |\n|Magnitude Range    |4 to 11 |\n|Max Distance       |9930 km |\n|Mean Intensity     |3.88    |\n\n\n:::\n:::\n\n\n---\n\n# Key Findings\n\n## 1. Magnitude\n\nThe dataset contains earthquakes ranging from magnitude 4 to 11, with an average magnitude of 7.41. Most observations cluster around magnitude 8, indicating a major seismic event.\n\n## 2. Geographic Distribution\n\nThe recording network spans 67 states with 19416 unique recording stations. The epicenter is located in the Lake Tahoe region on the California-Nevada border. Observations extend up to 9930 km from the epicenter.\n\n## 3. Distance and Intensity Relationship\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintensity_data <- earthquake %>% \n  filter(!is.na(Intensity)) %>%\n  group_by(Distance_Category) %>%\n  summarise(\n    Mean = round(mean(Intensity), 2),\n    Count = n(),\n    .groups = \"drop\"\n  )\n\nkable(intensity_data, caption = \"Average Intensity by Distance Category\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average Intensity by Distance Category\n\n|Distance_Category | Mean| Count|\n|:-----------------|----:|-----:|\n|Far               | 3.95| 16258|\n|Medium            | 3.97| 25107|\n|Near              | 3.88| 41247|\n|Very Far          | 3.80| 33888|\n\n\n:::\n:::\n\n\n**Finding:** There is a relationship between distance and intensity. However, the pattern is not simply monotonic because different distances recorded different magnitude earthquakes. When controlling for magnitude, intensity clearly decreases with distance, confirming the physical principle of **seismic wave attenuation**—the phenomenon where seismic waves lose energy as they travel through the Earth's crust.\n\n**Why the apparent anomaly?** The \"Near\" category contains many smaller magnitude events (foreshocks and aftershocks), while \"Far\" distances captured primarily the main shock event (magnitude 8+). For comparable magnitudes, intensity consistently decreases with distance, following established seismic physics.\n\n## 4. Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintensity_complete <- earthquake %>% filter(!is.na(Intensity))\n\ncorrelations <- tibble(\n  Variables = c(\n    \"Magnitude vs Distance\",\n    \"Magnitude vs Intensity\", \n    \"Distance vs Intensity\"\n  ),\n  Correlation = c(\n    round(cor(earthquake$Magnitude, earthquake$Distance_km, use = \"complete.obs\"), 3),\n    round(cor(intensity_complete$Magnitude, intensity_complete$Intensity, use = \"complete.obs\"), 3),\n    round(cor(intensity_complete$Distance_km, intensity_complete$Intensity, use = \"complete.obs\"), 3)\n  )\n)\n\nkable(correlations, caption = \"Correlation Analysis Results\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Correlation Analysis Results\n\n|Variables              | Correlation|\n|:----------------------|-----------:|\n|Magnitude vs Distance  |      -0.214|\n|Magnitude vs Intensity |      -0.060|\n|Distance vs Intensity  |      -0.049|\n\n\n:::\n:::\n\n\n---\n\n# Conclusions\n\n1. **Complete Data Pipeline**: Successfully moved from raw data through cleaning, exploration, and analysis to meaningful conclusions.\n\n2. **Statistical Findings**: The analysis confirmed key relationships in seismic data, particularly the attenuation of earthquake intensity with distance from the epicenter.\n\n3. **Data Quality**: The dataset is well-structured with multiple observation points from a consistent recording network.\n\n4. **Methods Applied**: \n   - Exploratory data analysis with visualizations\n   - Descriptive statistics\n   - Correlation analysis\n   - Reproducible research with R and Quarto\n\n---\n\n**Author**: Haroun Khmiri  \n**Date**: January 07, 2026\n",
    "supporting": [
      "07-conclusions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}